import os
import json
import io
import re
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from youtube_transcript_api import YouTubeTranscriptApi
import google.generativeai as genai
from pptx import Presentation
from pptx.util import Inches, Pt

app = Flask(__name__)
CORS(app)  # السماح لبلوجر بالاتصال بنا

# ================= CONFIGURATION =================
# ضع مفتاحك هنا
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY", "YOUR_API_KEY_HERE")
genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel('gemini-1.5-flash')

# ================= HELPER FUNCTIONS =================
def get_video_id(url):
    """استخراج ID الفيديو من الرابط"""
    if "v=" in url:
        return url.split("v=")[1].split("&")[0]
    elif "youtu.be" in url:
        return url.split("/")[-1]
    return None

def get_transcript(video_id):
    """جلب النص من اليوتيوب"""
    try:
        # نحاول جلب النص بالعربية، الإنجليزية، أو الألمانية
        transcript_list = YouTubeTranscriptApi.get_transcript(video_id, languages=['ar', 'en', 'de'])
        full_text = " ".join([i['text'] for i in transcript_list])
        return full_text
    except Exception as e:
        return None

def create_pptx(slides_data):
    """رسم ملف البوربوينت في الذاكرة"""
    prs = Presentation()
    
    # 1. شريحة العنوان
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = slides_data.get('title', 'Video Summary')
    subtitle.text = "Generated by Learn with Taha"

    # 2. شرائح المحتوى
    bullet_slide_layout = prs.slide_layouts[1]
    
    for slide_content in slides_data.get('slides', []):
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        title_shape.text = slide_content.get('header', '')
        
        # ضبط اتجاه النص (يمين لليسار للعربية) لو أمكن، لكن هنا سنبقيه قياسياً
        body_shape = shapes.placeholders[1]
        tf = body_shape.text_frame
        
        points = slide_content.get('points', [])
        if points:
            tf.text = points[0]
            for point in points[1:]:
                p = tf.add_paragraph()
                p.text = point

    pptx_io = io.BytesIO()
    prs.save(pptx_io)
    pptx_io.seek(0)
    return pptx_io

# ================= ROUTES =================

@app.route('/')
def home():
    return "LearnWithTaha API is Running!"

@app.route('/process', methods=['POST'])
def process_video():
    """
    نقطة واحدة تقوم بالعمليتين: تلخيص نصي + تجهيز رابط للبوربوينت
    """
    data = request.get_json()
    video_url = data.get('url')
    action_type = data.get('type') # 'summary' or 'ppt'

    video_id = get_video_id(video_url)
    if not video_id:
        return jsonify({"error": "رابط يوتيوب غير صحيح"}), 400

    transcript = get_transcript(video_id)
    if not transcript:
        return jsonify({"error": "عذراً، هذا الفيديو لا يحتوي على ترجمة نصية (Captions) ولا يمكن تحليله."}), 404

    # إذا كان الطلب تلخيص نصي فقط
    if action_type == 'summary':
        prompt = f"""
        Act as a professional tutor. Summarize this transcript.
        Transcript: {transcript[:15000]} 
        Format: Return a clean summary in Markdown format.
        Language: Detect language and reply in the same language (Arabic/English/German).
        """
        response = model.generate_content(prompt)
        return jsonify({"result": response.text})

    # إذا كان الطلب ملف بوربوينت
    elif action_type == 'ppt':
        prompt = f"""
        Analyze this transcript and create a PowerPoint structure.
        Transcript: {transcript[:15000]}
        
        Output strictly valid JSON:
        {{
            "title": "Main Title",
            "slides": [
                {{"header": "Slide 1", "points": ["point 1", "point 2"]}},
                {{"header": "Slide 2", "points": ["point 1", "point 2"]}}
            ]
        }}
        Do not use markdown code blocks. Just Raw JSON.
        """
        response = model.generate_content(prompt)
        try:
            clean_json = response.text.replace('```json', '').replace('```', '').strip()
            slides_data = json.loads(clean_json)
            
            # نحن هنا لا نعيد الملف مباشرة، بل نعيد البيانات للواجهة
            # (في التطبيق الحقيقي المعقد ننشئ رابط تحميل، لكن للسهولة سنرسل البيانات ونبني الملف أو نرسله كـ Base64)
            # *تعديل للاحترافية:* سنقوم بإنشاء الملف وإرساله كملف
            
            pptx_file = create_pptx(slides_data)
            return send_file(
                pptx_file,
                as_attachment=True,
                download_name='LearnWithTaha_Summary.pptx',
                mimetype='application/vnd.openxmlformats-officedocument.presentationml.presentation'
            )
            
        except Exception as e:
            return jsonify({"error": "فشل في إنشاء الملف: " + str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)